---
title: "otp-repo"
author: "Evelyn Gao"
date: "2/19/2022"
output: html_document
---

Good thing:
The practice on the class is really helpful. Since this time I solved a lot questions during the class, the test code of cipher is not so hard to write.
The video in the LinkedIn is also helpful. 
I have installed the git during the class so it doesn't cost me a lot of time.
Bad thing:
I have initialize the git repository but I still feel a little confused about the git, so I might need to watch the video more times. 
Also, I am still figure out how to push OPT repo with unit tests to github. (update: I succeed!) 
Besides, due the success at the beginning, I didn't finish my homework until Saturday, so I have missed a lot of TA time to solve my problems.
Better thing:
Try to write homework earlier and give myself sometime to go to TA hours.
Utilize the video shared in the class. 

Instruction:

Main cipher program:
In this cipher.py, I use the method taught in the class to run the program from the command line.
Basically, I use the mode same as the given example.

"-m": shows mamual

"-p": type "-p" and the size of one-time-pad you want, and it will generate pad and save it into One_time_pad.txt
eg: -p 1000 (generate One_time_pad.txt which contains pad of size 1000)

"-e": encipher command. Type filename you want to encipher. Use it combined with command "-w", and encipher with given pad file. Save it to encrypted-message.txt.

"-d": decipher command. Type filename you want to decipher. Use it combined with command "-w", and decipher with given pad file. Save it to decrypted-message.txt.

"-w": Type filename as pad. Use it with command "-e" or "-d"
eg: -e unencrypted.txt -w One_time_pad.txt
    -d encrypted.txt -w One_time_pad.txt
    
    
unit_test:

Generate "One_time_pad.txt" by generatePad() to use as pad and save it for later test.

Create a file called "encipherTest.txt", write message to it as test tool.

Create "encrypted-message.txt" to test encipher "encipherTest.txt" by using "One_time_pad.txt".

Use encrypted message in the "encrypted-message.txt" as "decipherTest.txt"

Create "decrypted-message.txt" to test decipher "decipherTest.txt" by using "One_time_pad.txt"

In this way, if the encipher and decipher method work, messages in the "encipherTest.txt" should be same as messages in the "decrypted-message.txt", and messages in the "decipherTest.txt" should be same as messages in the "encrypted-message.txt". Also, the pad in the "One_time_pad.txt" should be same as the result of generatePad().

If all the methods works, all the assumption above will be true and tests will pass.

(The message in the "encipherTest.txt" include uppercase, lowercase, punctuation to examine the correctness of decipher and encipher)
